import React from 'react';
import { ReportRenderer } from './ReportRenderer';
import { CitationList } from './CitationList';
import { Download, FileText, Calendar, Clock } from 'lucide-react';

interface Citation {
  id?: string | number;
  title: string;
  url: string;
  source?: string;
  source_agent?: string;
  date?: string;
}

interface ReportContainerProps {
  title?: string;
  content: string;
  citations?: Citation[];
  createdAt?: Date;
  onDownloadMarkdown?: () => void;
  onDownloadPDF?: () => void;
  isLoading?: boolean;
}

export const ReportContainer: React.FC<ReportContainerProps> = ({
  title,
  content,
  citations = [],
  createdAt,
  onDownloadMarkdown,
  onDownloadPDF,
  isLoading = false,
}) => {
  return (
    <div className="bg-gray-800 rounded-2xl overflow-hidden shadow-xl print-container">
      <header className="bg-gradient-to-r from-slate-900 to-slate-800 text-white py-8 px-6 md:py-12">
        <div className="max-w-4xl mx-auto">
          {title && (
            <h1 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-4 leading-tight">
              {title}
            </h1>
          )}
          <div className="flex flex-wrap items-center gap-4 text-slate-300 text-sm">
            <div className="flex items-center gap-2">
              <FileText className="w-4 h-4" />
              <span>Meta Deep Research Report</span>
            </div>
            {createdAt && (
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4" />
                <span>{createdAt.toLocaleDateString()}</span>
              </div>
            )}
            {citations.length > 0 && (
              <div className="flex items-center gap-2">
                <span>{citations.length} sources cited</span>
              </div>
            )}
          </div>
          
          {(onDownloadMarkdown || onDownloadPDF) && (
            <div className="flex flex-wrap gap-3 mt-6 no-print">
              {onDownloadMarkdown && (
                <button
                  onClick={onDownloadMarkdown}
                  className="inline-flex items-center gap-2 px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg text-sm font-medium transition-colors"
                >
                  <Download className="w-4 h-4" />
                  Download Markdown
                </button>
              )}
              {onDownloadPDF && (
                <button
                  onClick={onDownloadPDF}
                  className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 rounded-lg text-sm font-medium transition-colors"
                >
                  <Download className="w-4 h-4" />
                  Download PDF
                </button>
              )}
            </div>
          )}
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 md:px-6 py-8 md:py-12 bg-gray-700">
        {isLoading ? (
          <div className="flex items-center justify-center py-12">
            <div className="flex items-center gap-3 text-gray-400">
              <Clock className="w-5 h-5 animate-spin" />
              <span>Generating report...</span>
            </div>
          </div>
        ) : (
          <>
            <ReportRenderer content={content} />
            {citations.length > 0 && <CitationList citations={citations} />}
          </>
        )}
      </main>

      <footer className="border-t border-gray-600 py-6 px-6 no-print bg-gray-800">
        <div className="max-w-4xl mx-auto text-center text-sm text-gray-400">
          <p>Generated by Meta Deep Research</p>
          <p className="mt-1 text-xs text-gray-500">
            Synthesized from Gemini, OpenAI, and Perplexity research agents
          </p>
        </div>
      </footer>
    </div>
  );
};

export default ReportContainer;
